### ISSUE TITLE
Install pyrealsense

### ISSUE THREAD

**Issue by weiguochow** [guohengkai/region-ensemble-network#12]
@guohengkai 

Thanks for sharing your code. There is some errors when installed the pyrealsense, can you give me the operations in details?

regards,
weiguo

Windows specifics: set environment variable PYRS_INCLUDES to the rs.h directory location and environment variable PYRS_LIBS to the librealsense binary location. You might also need to have stdint.h available in your path.

**Comment by xinghaochen** [comment]
Hi, we just follow the [official documents](http://pyrealsense.readthedocs.io/en/master/readme.html#prerequisites) to install pyrealsense.
Could you provide more details of the errors you encountered?

**Comment by weiguochow** [comment]
@xinghaochen 

Hi, Thank you for your response. The version of the librealsense used is 2.2. Is it matter for these errors?
And the errors posted following. There are many similar errors like this for losing rs.h file.
regards,
weiguo


 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from pyrealsense/rsutilwrapper.cpp:576:0:
pyrealsense/rsutilwrapper.h:3:34: error: variable or field ‘_apply_depth_control_preset’ declared void
 void _apply_depth_control_preset(rs_device * device, int preset);
                                  ^
pyrealsense/rsutilwrapper.h:3:34: error: ‘rs_device’ was not declared in this scope
pyrealsense/rsutilwrapper.h:3:46: error: ‘device’ was not declared in this scope
 void _apply_depth_control_preset(rs_device * device, int preset);
                                              ^
pyrealsense/rsutilwrapper.h:3:54: error: expected primary-expression before ‘int’
 void _apply_depth_control_preset(rs_device * device, int preset);
                                                      ^
pyrealsense/rsutilwrapper.h:4:26: error: variable or field ‘_apply_ivcam_preset’ declared void
 void _apply_ivcam_preset(rs_device * device, rs_ivcam_preset preset);

**Comment by guohengkai** [comment]
@weiguochow Hi, may be you should post an issue on the repo of pyrealsense (https://github.com/toinsson/pyrealsense) instead. Thanks.
