### ISSUE TITLE
solver.prototxt

### ISSUE THREAD

**Issue by weiguochow** [guohengkai/region-ensemble-network#15]
Dear hengkai,
Can you share the solver.prototxt file that used to train the networks? I want to run the architecture described in the paper.
regards,
weiguo

**Comment by guohengkai** [comment]
Hi, the training details are all provided in the papers. Here are the main parts of solver.prototxt:
```
base_lr: 0.001
lr_policy: "step"
gamma: 0.1
stepsize: 40000
display: 100
max_iter: 160000
momentum: 0.9
weight_decay: 0.0005
```

**Comment by weiguochow** [comment]
Thank you!!!
regards
