### ISSUE TITLE
Annotation error on NYU dataset

### ISSUE THREAD

**Issue by weiguochow** [guohengkai/region-ensemble-network#18]
Hi, thank you for your code. And it works well on ICVL dataset. However, I found there is some error on NYU dataset. Hand joint position is correct, but the line is error with the start point. Can you give the more information on annotation of 14 hand pose joints of the NYU dataset which you used to train? 

```
def get_sketch_setting(dataset):
    if dataset == 'icvl':
        return [(0, 1), (1, 2), (2, 3), (0, 4), (4, 5), (5, 6),
                (0, 7), (7, 8), (8, 9), (0, 10), (10, 11), (11, 12),
                (0, 13), (13, 14), (14, 15)]
    elif dataset == 'nyu':
        return [(0, 1), (0, 2), (0, 5), (3, 4), (4, 5), (0, 7), (6, 7),
                (0, 9), (8, 9), (0, 11), (10, 11), (0, 13), (12, 13)]
    elif dataset == 'msra':
        return [(0, 1), (1, 2), (2, 3), (3, 4), (0, 5), (5, 6), (6, 7), (7, 8),
                (0, 9), (9, 10), (10, 11), (11, 12), (0, 13), (13, 14), (14, 15), (15, 16),
                (0, 17), (17, 18), (18, 19), (19, 20)]
```

**Comment by xinghaochen** [comment]
Hi, thanks for pointing out. There was a bug in the code. 
You can change the sketch setting of NYU to:
`[(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (9, 10), (1, 13),
                (3, 13), (5, 13), (7, 13), (10, 13), (11, 13), (12, 13)]`
We will soon fix this bug in the repo. 
Besides, the 14 hand joints of NYU dataset is chosen from the original 36 joints using the indices:
`[0,3,6,9,12,15,18,21,24,25,27,30,31,32]`
following the protocol of previous work.
Hope it helps.
