### ISSUE TITLE
About DATA Preprocessing。

### ISSUE THREAD

**Issue by EEWenbinWu** [guohengkai/region-ensemble-network#2]
@guohengkai @xinghaochen THx!Your Paper is helpful for my study.But there are some trouble for me about the data preprocessing.Could you tell me some detail about how you do the data preprocessing?

**Comment by guohengkai** [comment]
Hi, thank you for your interest. The details are in _crop_image func of hand_model.py.

**Comment by EEWenbinWu** [comment]
@guohengkai Thanks very much!
