### ISSUE TITLE
label normalization

### ISSUE THREAD

**Issue by EEWenbinWu** [guohengkai/region-ensemble-network#28]
thx a lot for your paper!
Here comes the question,how you normalized the joints according to the cropping?
thx again and hope for your reply.

**Comment by guohengkai** [comment]
Hi, we use the center and the scale to normalize them. See here for details: https://github.com/guohengkai/region-ensemble-network/blob/master/evaluation/hand_model.py#L98.

**Comment by EEWenbinWu** [comment]
> Hi, we use the center and the scale to normalize them. See here for details: https://github.com/guohengkai/region-ensemble-network/blob/master/evaluation/hand_model.py#L98.

So the label you regressed is the normalized (u,v,d) from the full image? I was puzzled by this, why don't you regress the (u,v,d) from the croped 2D area? thx for your reply!

**Comment by guohengkai** [comment]
@EEWenbinWu We regress the (u, v, d) from the cropped 2D image.

**Comment by EEWenbinWu** [comment]
thx! you said that  _transform_pose is used to convert normalized coordinates (u, v, d) in cropped image into (u, v, d) in full image coordinates.
but why converting normalized coordinates (u, v, d) in cropped image into (u, v, d) in full image coordinates have to use the _fx?

**Comment by EEWenbinWu** [comment]
In my own understanding, we can get the coordinates (u, v, d) in cropped image by this way:
u_croped = u_full - x_start.
is it work?

**Comment by guohengkai** [comment]
We use cube for cropping, which is in world coordinates. So we should first use focal length to convert it into the image coordinates. The centers in "_transform_pose" are the cube centers in the full image. The function is used to convert the predicted local coordinates into full image coordinates.

**Comment by EEWenbinWu** [comment]
thank you so much，I know these，but I was still puzzled by the output of your network.Sorry
, My English is poor




| |
吴文斌
邮箱：wenbinwuee@163.com
|

签名由 网易邮箱大师 定制

On 01/02/2019 17:16, Hengkai Guo wrote:

We use cube for cropping, which is in world coordinates. So we should first use focal length to convert it into the image coordinates. The centers in "_transform_pose" are the cube centers in the full image. The function is used to convert the predicted local coordinates into full image coordinates.

**Comment by guohengkai** [comment]
@EEWenbinWu For example:
x' = (x - center_x) * center_z / (fx * cube_size)

**Comment by EEWenbinWu** [comment]
According to the "_transform_pose" , the x' = (x - center_x) * center_z / fx / cube_size, what i can’t understand is why this operation can convert  the full image coordinates into the cropped coordinates. the x  is in image coordinates but the center_x is in world coordinates.

**Comment by guohengkai** [comment]
center_x is in image coordinates. You can see: https://github.com/guohengkai/region-ensemble-network/blob/master/evaluation/util.py#L126 for the computation of centers.

**Comment by EEWenbinWu** [comment]
OK，so (x - center_x) * center_z / fx convert  the full image coordinates  x into the cropped coordinates in mm and then normalized by the cube_size in mm?

**Comment by guohengkai** [comment]
Because the cube_size is in world coordinates, we should convert it into image coordinates. That is done by:
cube_size_in_image = cube_size * fx / center_z

Then we can use it to normalize:
x' = (x - center_x_in_image) / cube_size_in_image

Sorry for the confusion.

**Comment by EEWenbinWu** [comment]
I see it! Thank you so much again!

**Comment by EEWenbinWu** [comment]
sorry for disturbing you again, when you train your network, how you get the center? Is it from the "get_center"?

**Comment by guohengkai** [comment]
Sure. The function is consistent with our C++ implementation.

**Comment by EEWenbinWu** [comment]
thank you and good luck to you!
