### ISSUE TITLE
About the loss function

### ISSUE THREAD

**Issue by wishinger-li** [guohengkai/region-ensemble-network#6]
hi:
    excellent job！！ 
    I want to retrain the model , is it convenient for you to tell me the loss function.
    I did not see the info about loss function neither in the paper nor in the model folder(only deploy prototxt)
    thank you !

**Comment by guohengkai** [comment]
Hi, we use Smooth L1 Loss. See our newly paper (https://arxiv.org/abs/1707.07248) for details. Thanks.
