### ISSUE TITLE
nyu数据集下载总是中断，请问除了官方的数据源还有没有其他下载方式或者国内的镜像？十分感谢！！

### ISSUE THREAD

**Issue by PengfeiRen96** [guohengkai/region-ensemble-network#8]

**Comment by guohengkai** [comment]
Sorry, I used the official data source of NYU as well. I don't know if there exists any other ways.

**Comment by PengfeiRen96** [comment]
那请问你用什么下载工具下得啊？我很绝望啊。。。

**Comment by guohengkai** [comment]
直接在Linux下用wget下载的，可能是因为我用教育网的缘故？或者你试试VPN？

**Comment by PengfeiRen96** [comment]
好的，非常感谢。我用的网也应该是教育网啊，但是我就是下不下来，我先用服务器下试试吧。
